### ISSUE TITLE
Peer-to Peer Code review.

### ISSUE THREAD

**Issue by SiveMdluli** [fezzopro/portfolio-mobile-first#10]
Both your mobile and desktop versions of your portfolio is fantastic 🥇 💯 
However, there's always room for improvement, check the comments below for areas you can make a few tweaks for your project to be even more awesome 🔥 

*The "let's connect" text and the social icons need to be in separate rows instead of one row. 

* Align the language(s) images toward the left instead of the center, to resemble the template.
* Insert a font of 'Poppins' in the textarea, so that when a user sends you a message, the read font, and the typed font is uniform.

**Comment by fezzopro** [comment]
Thank you for your feedback guys 🚀
