### ISSUE TITLE
Review of UI and Suggestions

### ISSUE THREAD

**Issue by Abdulwhbhussain** [fezzopro/portfolio-mobile-first#4]
Everything was Great about the UI,
But Here are Some Suggestions to make it more Better:

1- You need to work on your Navbar; it is showing Ham Burger Menu Icon instead of Menu Links in Desktop version;
2- You Need to Switch the Position of Elements in (2015 , CANOPY);
3- You need to Work on Language Section; Use Display Flex and give it 60% of available space;
4- You need to Work on Get My Resume Button, you should set its Margin and Padding;
5- You need to Work on the Contact Section the Flex/Grid is Streching to the 70% part of Screen; you need to Reduce it to 30%;
6- You need to work on submit/send/contact Button.

**Comment by fezzopro** [comment]
Thank you for the feedback guys 🚀
